### ISSUE TITLE
BrayDog210 Doesn't know what licensing is and is a abosulte fool for asking someone else to do this

### ISSUE THREAD

**Issue by BrayDog2010** [souldbminersmwc/chipped-x-create-fabric#1]
I'm the owner of Crafting Recipes For Create mod and can you add a link back to my mod. Thank You.

**Comment by alfonsojon** [comment]
Seems that this is the actual original - https://www.curseforge.com/minecraft/texture-packs/chipped-create-compatibility

**Comment by BrayDog2010** [comment]
I'm not affiliated with that texture pack, I'm the creator of the mod [Crafting Recipes For Create](https://modrinth.com/mod/crafting-recipes-for-create/versions )

**Comment by souldbminerr** [comment]
Just stop. Please. You stole my code already, and I did credit you on MR.

**Comment by BrayDog2010** [comment]
I did not steal your code

**Comment by souldbminerr** [comment]
Please stop denying it. The class names, the files and structure is the same. I have relicensed CHCF to Affero GPL, please comply with the relisence
